### ISSUE TITLE
Discrepancy between README and benchmarks.png

### ISSUE THREAD

**Issue by felangel** [jonataslaw/benchmarks#2]
Hi 👋 
I can’t seem to understand how the graphic (benchmarks.png) and the data points in the README are related. Can you please provide some information about what the x-axis units are in the graphic and how the two are related? Thanks 👍

**Comment by jonataslaw** [comment]
> Hi 
> I can’t seem to understand how the graphic (benchmarks.png) and the data points in the README are related. Can you please provide some information about what the x-axis units are in the graphic and how the two are related? Thanks


Hi Felix, it's a pleasure to have you here.
The rest app takes up 4mb of RAM.
After changing the state of a list 10 times, the RAM usage was measured, and then the collector was manually cleaned and the ram was measured again.
If you want to make modifications to the part of your lib for better use, you can feel free (maybe you have a better way of using your lib). And if you have tests with different numbers on different devices, you can print that I include as well.

Remembering that the tests are done in profile mode, the debug mode is not necessary.
Any questions I will be here.

**Comment by felangel** [comment]
Hi @jonataslaw thanks for the quick response. So I'm still unclear about how the chart correlates to the numbers in the README. For example, based on the chart it appears provider uses 1.5 (mb?) of RAM while get uses ~1.3 (mb?) however in the README the numbers are as follows:

# No GC
Provider = 4.55
Get = 4.53

# GC
Provider = 4.15
Get = 4.14

Are the numbers in the README reflected in the chart? If not, which one is accurate and can we please ensure the metrics being communicated are consistent and accurate? Thanks 🙏

**Comment by jonataslaw** [comment]
The difference is from the Provider to GetX:

Provider = 4.15 
Get = 4.14
GetX = 4.13

However, I think you pointed out something that is spelled wrong. The difference is between 150kb, not 1.5mb.
The proportion remains the same as it was measured with the addition, not with the total size of the app, but the nomenclature is wrong. Thanks for pointing this out, and feel free to suggest improvements, as well as doing PRs. The purpose of this is to have an indicative, and even point out possible improvements that can be made in each package.
And congratulations on BLoC, of ​​all State Managers, it is without a doubt the best documentation of all, it is something that inspires any package, things are very well written and explained, it is amazing how anything is documented. I really admire your work.

**Comment by jonataslaw** [comment]
Fix on last update
